#MyBeans Cashier Settings
#Wed Mar 11 19:02:34 WIB 2026
ItemCost_0=4055
ItemCost_1=7840
ItemCost_2=9153
ItemCost_3=8000
ItemCost_4=8000
ItemCount=5
ItemName_0=Americano
ItemName_1=Dalgona
ItemName_2=Milk Coffee
ItemName_3=Pudding Ori
ItemName_4=Pudding Regal
ItemPrice_0=10000
ItemPrice_1=15000
ItemPrice_2=18000
ItemPrice_3=12000
ItemPrice_4=13000
saveDir=G\:\\My Drive\\MyBeans\\Log\\
