#MYBEANS CASHIER Configuration Profile
#Sat Mar 14 14:42:20 WIB 2026
AccentColor=-2358785
Buyers=Christian,Ven,Jowie
DarkMode=true
ItemCost_0=4055
ItemCost_1=7840
ItemCost_2=9153
ItemCost_3=9000
ItemCost_4=9000
ItemCount=5
ItemName_0=Americano
ItemName_1=Dalgona
ItemName_2=Milk Coffee
ItemName_3=Pudding Caramel
ItemName_4=Pudding Regal
ItemPrice_0=10000
ItemPrice_1=15000
ItemPrice_2=18000
ItemPrice_3=12000
ItemPrice_4=13000
Language=EN
MenuExpanded=true
StoreName=MYBEANS CASHIER
saveDir=G\:\\My Drive\\MyBeans\\Log\\
